Repository AY1920S2-CS2113T-M16-2/tp, pull requests merged in 2020-04, with the labels that each got.

#227 PE Dry Run Bug Fix - AddRecipeCommand
  KitchenLogs.log
  KitchenLogs.log.1
  KitchenLogs.log.2
  KitchenLogs.log.3
  KitchenLogs.log.3.lck
  KitchenLogs.log.lck
  outputIngredient.txt
  outputRecipe.txt
  src/main/java/seedu/kitchenhelper/command/CookRecipeCommand.java
  src/main/java/seedu/kitchenhelper/parser/Parser.java
Labels: type.Bug

#244 PE Dry Run Bug Fix - Deduct Quantity in CookRecipeCommand
  KitchenLogs.log
  KitchenLogs.log.lck
  outputChore.txt
  outputIngredient.txt
  outputRecipe.txt
  src/main/java/seedu/kitchenhelper/command/CookRecipeCommand.java
  src/test/java/seedu/kitchenhelper/command/DeleteIngredientCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#245 PE Dry Run Bug Fix - Deletion User Guide
  KitchenLogs.log
  docs/UserGuide.md
  outputIngredient.txt
Labels: type.Bug, type.Documentation

#250 Fix leading and trailing space
  KitchenLogs.log
  outputRecipe.txt
  src/main/java/seedu/kitchenhelper/object/Recipe.java
Labels: type.Bug

#249 UG: update cookRecipe
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#248 DG: Updated sequence diagram and explanation
  docs/DeveloperGuide.md
  docs/images/addRecipeSequenceDiagram.png
Labels: type.Documentation

#256 Fix bugs - leading and trailing spaces in category
  KitchenLogs.log.1
  KitchenLogs.log.1.lck
  src/main/java/seedu/kitchenhelper/parser/Parser.java
Labels: type.Bug

#257 Minor edit to User guide - removal of echo commands
  docs/UserGuide.md
Labels: type.Documentation
