Repository AY1920S2-CS2113T-M16-2/tp, pull requests merged in 2020-03, with the labels that each got.

#94 User guide for addrecipe and minor spacing issue
  docs/UserGuide.md
Labels: type.Documentation

#103 Added in User Guide for Deletion of ingredients and recipes
  KitchenLogs.log
  docs/UserGuide.md
  outputIngredient.txt
Labels: type.Documentation

#102 Developer guide draft
  docs/DeveloperGuide.md
Labels: type.Documentation

#104 Branch fix userguide bugs
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#106 Branch developerguide
  docs/DeveloperGuide.md
Labels: type.Documentation

#126 Update Developer Guide
  docs/DeveloperGuide.md
  docs/images/AddRecipe1.png
  docs/images/AddRecipe2.png
  docs/images/AddRecipe3.png
  docs/images/AddRecipe4.png
  docs/images/UI_Component.png
Labels: type.Documentation

#155 UG reformat
  docs/UserGuide.md
Labels: type.Documentation

#161 Branch bug fix
  KitchenLogs.log.1
  KitchenLogs.log.1.lck
  KitchenLogs.log.2
  KitchenLogs.log.lck
  src/main/java/seedu/kitchenhelper/command/SearchChoreCommand.java
  src/main/java/seedu/kitchenhelper/command/SearchIngredientCommand.java
  src/main/java/seedu/kitchenhelper/command/SearchRecipeCommand.java
  src/main/java/seedu/kitchenhelper/exception/KitchenHelperException.java
Labels: type.Bug

#162 Fixed bug in adding unknown category for addrecipe
  KitchenLogs.log
  KitchenLogs.log.1
  KitchenLogs.log.1.lck
  KitchenLogs.log.lck
  outputRecipe.txt
  src/main/java/seedu/kitchenhelper/object/Recipe.java
  src/main/java/seedu/kitchenhelper/parser/Parser.java
Labels: type.Bug
